export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Restore sane tty settings
if [ -n "$SSH_TTY" ]; then
    stty sane
fi

# PATH
export PATH="/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"

# Editor
export EDITOR=vim

# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY

# Completion
autoload -Uz compinit && compinit
setopt AUTO_PARAM_SLASH
zstyle ':completion:*' special-dirs true

# fzf
source /opt/local/share/fzf/shell/key-bindings.zsh
source /opt/local/share/fzf/shell/completion.zsh

# Modern replacements
alias ls='eza'
alias ll='eza -lg --group-directories-first --sort=ext'
alias cat='bat --style=plain --paging=never'
alias gs='git status'

copy() {
    printf "\033]52;c;%s\a" "$(base64 | tr -d '\n')"
}
alias c=copy

PS1='%F{22}%n@%m%f:%F{blue}%3~%f$ '       # Regular
# PS1='%B%F{22}%n@%m%f%b:%F{blue}%3~%f$ '   # Bold

export PATH="$HOME/.local/bin:$PATH"
export PATH="/opt/local/lib/ImageMagick7/bin:$PATH"

# Package managers
export PATH="$HOME/.cargo/bin:$PATH"
